---
abstract: 'Minimalist Data Validation for Moo'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Validate
requires:
  Moo: 0
  Validation::Class: 0
resources:
  bugtracker: https://github.com/alnewkirk/MooX-Validate/issues
  homepage: https://github.com/alnewkirk/MooX-Validate
  repository: git://github.com/alnewkirk/MooX-Validate.git
version: 0.000003
